### PR TITLE
Updating and Optimizing the prime number verification program

### PR DESCRIPTION
**Pull request by crackCodeLogn**

### CODE REVIEW

**Review by kal179 — CHANGES_REQUESTED** [review]
Hey Thanks for the changes, looks great , maybe you can add more documentation ! Then i'll merge it! Thanks again!

**Comment by crackCodeLogn** [comment]
Hmm, will try to add some comments.

**Comment by crackCodeLogn** [comment]
updated

**Comment by crackCodeLogn** [comment]
Is there a problem with the commit?

**Review by kal179 — APPROVED** [review]
Awesome thanks for changes, looks pretty cool!

**Pull request merged**
